# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: konrad.jelen@gmail.com
author_name: Stellars Henson
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyterlab_terminal_show_in_file_browser_extension
project_short_description: Jupyterlab extension to add context menu item to the terminal
    tab to navigate file browser to the pwd path of the terminal
python_name: jupyterlab_terminal_show_in_file_browser_extension
repository: ''
test: true

